version: '3.5'
services:
  integration-tools-python-producer-ms:
    build: .
    image: integration-tools-python-producer:latest
    container_name: integration-tools-python-producer-ms
    networks:
      - integration-tools-network
    environment:
      - ENV=local

networks:
  integration-tools-network:
    external:
      name: integration-tools-network

