spring:
  profiles:
    active: ${ENV}

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        recipient_topic_count:
          binder: kafka
          destination: recipient_topic
          group: count
          content-type: application/json
        recipient_topic_uf:
          binder: kafka
          destination: recipient_topic
          group: uf
          content-type: application/json
        recipient_topic_recipient:
          binder: kafka
          destination: recipient_topic
          group: recipient
          content-type: application/json

  output:
    ansi:
      enabled: ALWAYS

logging:
  file: logs/application.log
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %highlight(%-5level) - %cyan(%-40.40logger{40}) - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger: %msg%n"
  level:
    org.springframework: INFO
    root: ERROR
    com.fiap.integrationstools.consumer: ERROR
