spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka1:9092

  output:
    ansi:
      enabled: ALWAYS

logging:
  file: logs/application.log
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %highlight(%-5level) - %cyan(%-40.40logger{40}) - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger: %msg%n"
  level:
    org.springframework: INFO
    root: ERROR
    com.fiap.integrationstools.consumer: ERROR

